[env:rp2040_v3_codex]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
monitor_speed = 115200
board_build.core = earlephilhower
lib_deps =
  adafruit/Adafruit NeoPixel @ ^1.12.5
